name: Publish To Wally

on:
  release:
    types: [published]

jobs: 

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Release Tag
        run: | 
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ github.token }}

      - name: Install Aftman Toolchains
        run: aftman install

      - name: Install Dependencies
        run: wally install

      - name: Edit Wally Release
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "wally.toml"
          key: "package.version"
          value: ${TAG#v}

      # - name: Log in to wally
      #   env:
      #     WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
      #   run: |
      #     mkdir ~/.wally
      #     printenv WALLY_AUTH > ~/.wally/auth.toml
          
      # - name: Push update to wally
      #   run: wally publish
